server {
    listen 80;
    location /fixkostentracker/ {
        alias /usr/share/nginx/html/;
        index index.html;
        try_files $uri $uri/ /fixkostentracker/index.html;
    }
    location = / {
        return 302 /fixkostentracker/;
    }
}
